# vim: set ft=ruby

brew "aws-vault"
brew "awscli"
brew "bash"
brew "borders"
brew "diff-so-fancy"
brew "direnv"
brew "eza"
brew "fzf"
brew "gh"
brew "git"
brew "go"
brew "imagemagick"
brew "jq"
brew "lazydocker"
brew "lazygit"
brew "neovim"
brew "node"
brew "rbenv"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "stow"
brew "tmux"
brew "watch"
brew "wget"
brew "yamllint"
brew "yarn"
brew "zoxide"

tap "trobrock/trobrock"
brew "hush", restart_service: "always"

# UI
tap "FelixKratz/formulae"
brew "sketchybar"
cask "nikitabobko/tap/aerospace"
tap "sachaos/todoist"
brew "todoist"
cask "font-caskaydia-cove-nerd-font"

# Casks
cask "todoist"
cask "1password"
cask "1password-cli"
cask "raycast"
cask "firefox"
cask "orbstack"
